### ISSUE TITLE
Authorize.net token billing integration with CIM?

### ISSUE THREAD

**Issue by wrhansen** [thephpleague/omnipay-authorizenet#1]
It looks like Authorize.net has support for token billing with a feature called Customer Information Manager (CIM) that allows you to save customer information on their server, and later access it via a token.

Is there plans for Omnipay's token billing methods to support CIM for this gateway?

**Comment by kayladnls** [comment]
A separate customer object is being planned for V3.

**Comment by mansouralex** [comment]
Does the library now supports token billing for Authorize.net ?
