### ISSUE TITLE
Add support for retail data to AIMAuthorizeRequest

### ISSUE THREAD

**Issue by samlitowitz** [thephpleague/omnipay-authorizenet#101]
Add support for retail data (deviceType and marketType) to AIMAuthorizeRequest (and subsequently AIMPurchaseRequest). Authorize.Net allows retail data for both [authOnlyTransactions](https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card) and [authCaptureTransactions](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card).

**Comment by judgej** [comment]
Was auto-closed. Don't want to close until it is released.

**Comment by judgej** [comment]
Release 3.2.0
