### ISSUE TITLE
Add support for track data to AIMAuthorizeRequest

### ISSUE THREAD

**Issue by samlitowitz** [thephpleague/omnipay-authorizenet#103]
Add support for track data (track1 and track2) to AIMAuthorizeRequest (and subsequently AIMPurchaseRequest). Authorize.Net allows retail data for both [authOnlyTransactions](https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card) and [authCaptureTransactions](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card).

**Comment by judgej** [comment]
The PR was merged (with a number of changes) but has been released for a while now. Closing this issue.
