### ISSUE TITLE
Laravel 5.6 failed 

### ISSUE THREAD

**Issue by tonimitrevski** [thephpleague/omnipay-authorizenet#109]
Installation request for omnipay/authorizenet ~2.5.1 -> satisfiable by omnipay/authorizenet[2.5.1].
    - Can only install one of: symfony/http-foundation[v3.4.4, 4.0.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.5, 4.0.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.6, 4.0.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.7, 4.0.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.8, 4.0.x-dev].
    - laravel/framework 5.6.x-dev requires symfony/http-foundation ~4.0 -> satisfiable by symfony/http-foundation[v4.0.9, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.1.0-BETA1].

The problem is laravel 5.6 require Symfony 4 package . any solution?

**Comment by barryvdh** [comment]
Yeah this needs to be upgraded to support Omnipay 3.x, see https://github.com/thephpleague/omnipay-authorizenet/issues/108

**Comment by barryvdh** [comment]
Can you check with `3.x@dev`?

**Comment by tonimitrevski** [comment]
Another issue :) 

Problem 1
    - omnipay/common v3.0.2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.0 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-beta.3 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-beta.2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-beta.1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-alpha.4 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-alpha.3 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-alpha.2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-alpha.1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-RC2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0-RC1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common 3.0.x-dev requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/authorizenet 3.0.x-dev requires omnipay/common ^3 -> satisfiable by omnipay/common[3.0.x-dev, v3.0-RC1, v3.0-RC2, v3.0-alpha.1, v3.0-alpha.2, v3.0-alpha.3, v3.0-alpha.4, v3.0-beta.1, v3.0-beta.2, v3.0-beta.3, v3.0.0, v3.0.1, v3.0.2].
    - Installation request for omnipay/authorizenet 3.x@dev -> satisfiable by omnipay/authorizenet[3.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems

**Comment by barryvdh** [comment]
Please also require league/omnipay

`composer require league/omnipay:^3 omnipay/authorizenet:"3.x@dev"`

**Comment by tonimitrevski** [comment]
Thanks 🥇
