### ISSUE TITLE
Invalid paths for AIM query messages

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-authorizenet#125]
From @dmgctrlr on issue #79

------

Hi @eileenmcnaughton
I've been trying to use your `$gateway->query(array('startTimestamp' => strtotime('yesterday'), 'endTimeStamp' => 'strtotime('now')));` example. I'm receiving a InvalidRequestException. I believe this is due to the AIMAbstractRequest class adding a transaction type. Do we perhaps need to add a method override for addTransactionType in the QueryRequest class?

In addition, it appears that in the AIMGateway class, calls to queryBatch, queryBatchDetail and queryDetail are not pointing to the correct files.

I may be misusing this, so please forgive my provisional understanding!

Sorry if this is not the correct place to post this, feel free to move it if required.

**Comment by judgej** [comment]
Path fixes in branch issue125. I've not looked at the first bit of the query yet. If you have any code examples to replicate this, that would be useful.

**Comment by dmgctrlr** [comment]
Hi @judgej thanks for your input. To replicate the error I am simply doing the following:

`
$gateway = Omnipay::create('AuthorizeNet_AIM');
$gateway->initialize(array_merge(['ApiLoginId' => '****', 'TransactionKey' => '****'],
        ['developerMode' => true, 'testMode' => true]));

    $request = $gateway->query([
        'startTimestamp' => strtotime('yesterday'), 'endTimeStamp' => strtotime('now')
    ]);

    $request->send();`

Which will trigger the InvalidRequestException, apparently here:
`Omnipay\\AuthorizeNet\\Message\\AIMAbstractRequest->addTransactionType(Object(SimpleXMLElement))`

I noticed in the AIMPaymentPlansQueryRequest there is an empty addTransactionType.

**Comment by judgej** [comment]
I've disabled the validation check by overriding the transaction type method in the "query" functions, if you would like to give it a try. I have not read up on the query functionality, so no no idea if it is actually working, i.e. doing what it was designed to do.

**Comment by dmgctrlr** [comment]
@judgej Yes, thats working well now! Thanks! When do you think that could be merged?

**Comment by eileenmcnaughton** [comment]
I think this makes sense - I haven't been in the code for a while but the logic above makes sense

**Comment by judgej** [comment]
I'll merge it into teh master branch now, and look at a release perhaps tomorrow.

**Comment by judgej** [comment]
In `master` now. If you could try it and let me know if it's working, I'll tag it for release. It'll probably be a patch version, since it fixes functionality that didn't work and nobody could possibly have been using as it stood.

**Comment by dmgctrlr** [comment]
@judgej Sorry for the delay, yes, it appears to be working as expected in master.

thanks again!

**Comment by judgej** [comment]
In `master` now. If you could try it and let me know if it's working, I'll tag it for release. It'll probably be a patch version, since it fixes functionality that didn't work and nobody could possibly have been using as it stood.

**Comment by judgej** [comment]
Release 3.2.0
