### ISSUE TITLE
Show example of passing CreditCard with auth.net

### ISSUE THREAD

**Issue by hexatex** [thephpleague/omnipay-authorizenet#135]
in your readme it states "You will still need to pass in the CreditCard object, as that contains details of the payee and recipient, but just leave the credit card details of that object blank. For example:" but then does not pass a CreditCard object. I am finding this instruction confusing.

**Comment by judgej** [comment]
Sorry, that is implied in the "..." - it's a standard Omnipay parameter that any gateway would use, so is kind of assumed. I'll try yo make it a little clearer.

**Comment by judgej** [comment]
Hopefully the addition to the example helps. Closing this issue for now, but feel free to re-opem if this is still not clear. Remember to read in conjuction with the main Omnipay docuentation https://omnipay.thephpleague.com/
