### ISSUE TITLE
Transaction ID

### ISSUE THREAD

**Issue by kyledye** [thephpleague/omnipay-authorizenet#17]
Hello,

I am trying to integrate Omnipay into CodeIgniter - I'm a seasoned PHP developer, but I am having some difficulty getting a transaction id from a Purchase or Authorization using the Authorize.net module.  If I run the ->getData() method on the response, I get a large array of values, which can be a little overwhelming.  Could you tell me which index is the TransactionID or if there is a method defined to get the transaction id from the response?

Thanks,

Kyle

**Comment by kayladnls** [comment]
Kyle, 

`$response->getTransactionReference();` should do it for you. Let me know if you have any further questions.

**Comment by kyledye** [comment]
Thank you Kayla! :)

**Comment by kyledye** [comment]
Sorry, but this did not work for the Authorize.net AIM api

**Comment by kayladnls** [comment]
The function should exist on your response object, as seen here.
https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/AIMResponse.php#L54-L57

Is it giving you a specific error, or just not working?

**Comment by pollen8** [comment]
I'm having the same issue for me it returns "0"
I'm currently just testing so have the following:

$gateway->setTestMode(true);
$gateway->setDeveloperMode(true);

The response variable seems to be an array and the transaction reference index at 37, not 4 as used in AIMResponse.php (line 46):

    public function getAuthorizationCode()
    {
        return $this->data[4];
    }

so I changed that to 

    public function getAuthorizationCode()
    {
        return $this->data[37];
    }

and for the test environment that works. I don't yet have a live account set up to test this on live though

**Comment by pollen8** [comment]
ok a quick look at the docs states that it is index 37. 
http://www.authorize.net/support/AIM_guide.pdf
see the section "Table 17 Payment Gateway Response Fields "

**Comment by pollen8** [comment]
woops sorry its not the getAuthorizationCode() but getTransactionReference()

see this pr 
https://github.com/pollen8/omnipay-authorizenet/pull/1

**Comment by neilcrookespm** [comment]
The current code works for me. To get a non-zero transaction ID turn test mode off. Provided developer mode is still on, you can use the test credit card numbers listed [here](http://developer.authorize.net/faqs/#testccnumbers) for successful transactions.

Click the response tab of the docs for [charging a card](http://developer.authorize.net/api/reference/#payment-transactions-charge-a-credit-card) and scroll down to the transId row...

> When testRequest is set to a positive response, or when Test Mode is enabled on the payment gateway, this value will be 0.

**Comment by judgej** [comment]
Can confirm, in test mode the transactionReference (sent as x_trans_id) will always be zero (for AIM and SIM at least). Similarly, the x_auth_code will be "000000".

Some gateways will send you a validly formatted transaction reference even in test mode, but not this one.

**Comment by judgej** [comment]
Can this be closed? It looks like it is working as it should.

**Comment by kyledye** [comment]
Yes it can be - thank you.
