### ISSUE TITLE
Authorizenet not pulling latest version with composer

### ISSUE THREAD

**Issue by kayladnls** [thephpleague/omnipay-authorizenet#20]
_From @Webvida on March 19, 2015 15:18_

composer require omnipay/authorizenet:~2.0

Does not pull the latest version? It does not contain the AIMRefundRequest.php file...

Thanks!

_Copied from original issue: thephpleague/omnipay#247_

**Comment by kayladnls** [comment]
Sorry about that. Just tagged a new minor, so it should pull it now.

**Comment by Webvida** [comment]
Omg! I thought I was going crazy - i just tested and the latest version appeared! But it was because you fixed it sooooo fast. KUDOS for the great response / support... that turnaround was less than 5 minutes... thank you thank you thank you

**Comment by zmonteca** [comment]
This is happening again. 

composer is pulling 2.4.2, but for some reason the master and what seems to be v2.4.2 doesn't have the method CIMGateway::deleteCard().

**Comment by judgej** [comment]
@zmonteca The method is here in `master` https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/CIMGateway.php#L54 What kind of problem are you seeing?

**Comment by zmonteca** [comment]
Exactly. My composer is fetching 2.4.2

per 

`
"require": {
     "omnipay/authorizenet": "~2.0"
}`

**Comment by zmonteca** [comment]
Got it. 

`"require": { "omnipay/authorizenet":` "master" } `

**Comment by judgej** [comment]
I see - sorry - I misunderstood what you were trying to do. There are changes in the master that you need to get to.

Be warned - I am just reverting a PR in master that I merged by mistake. Give it ten minutes and pull again.
