### ISSUE TITLE
Temporary live enpoint URLs - hotfix needed?

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-authorizenet#24]
Authorize.Net are in the process of moving their servers. This will involve some downtime on the current live endpoint URLs leading up to October 2015. This one, for example:

https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/AIMGateway.php#L24

    'liveEndpoint'      => 'https://secure.authorize.net/gateway/transact.dll',

To avoid the downtime, the URL can be changed to this *now* (from start of July), as this endpoint has already gone through the server migration process:

    https://secure2.authorize.net/gateway/transact.dll

Should we change this? Note that the endpoint URL *can* be set by hand when creating the gateway, so the merchant site can override it to use the `secure2` version. However, that would need a merchant site change, while doing so here would be a packageist "hotfix" change.

Obviously needs to be tested on a live site first - I'm happy to do that.

**Comment by judgej** [comment]
The complete message from Authorize.Net (annoyingly, no link to any online article I can find):

Important Authorize.Net Networking Change
  	

Dear Authorize.Net Developer:
  	

At Authorize.Net, the reliability of our platform is our first priority. Your business and your merchants' businesses depend on our services, and we understand how important that is. To that end, we are implementing a new networking solution that will provide merchants with a superior level of processing reliability.

Please read this email thoroughly.
Akamai Network Technology

Over the coming months, Authorize.Net will be upgrading access to the Internet connections that serve our data centers. Instead of allowing direct connections, all Internet traffic will be routed through Akamai, a third-party cloud network service that routes and delivers Internet traffic.

Using Akamai network technology will help decrease latency and improve the reliability of our payment gateway. It will also help safeguard against interruptions caused by issues beyond Authorize.Net's direct control, such as Internet congestion, fiber cable cuts and other similar issues. Additionally, come October, merchants connected to Akamai should no longer be affected by planned downtimes.
Implementation Plan And Timeline

We are implementing Akamai's technology into our network in two phases.

    Phase One (Now through June 2016) — We have created three new URLs for transaction processing that are hosted by Akamai. You can update your website or payment solution to point to the new transaction URLs today, which will provide the immediate benefits detailed above. Come October, merchants connected to Akamai should no longer be affected by planned downtimes.
    Phase Two (June 2016) — We will automatically direct all of our existing transaction processing URLs to connect through Akamai in June of 2016. After this change, all transaction URLs will connect to Authorize.Net through Akamai.

IMPORTANT: To take advantage of the uptime benefits Akamai offers, we recommend you proactively update your website or payment solution during Phase One rather than waiting to be automatically updated during Phase Two.
Updating Your Solution

The new Akamai transaction URLs that are available now are:

    https://api2.authorize.net/xml/v1/request.api
    https://api2.authorize.net/soap/v1/Service.asmx
    https://secure2.authorize.net/gateway/transact.dll

We will begin sending our initial emails about Akamai to merchants starting tomorrow.
Firewall And IP Address Considerations

If you do not use a firewall or do not connect directly via an IP address, then you can disregard this section.

Using Akamai technology, Authorize.Net's IP addresses will become dynamic rather than static. If your website or payment solution uses a firewall that has whitelisted Authorize.Net's IP address or connects to Authorize.Net directly via an IP address, you will need to make additional changes.

    Firewall Considerations — If your solution uses a firewall to filter outbound connections, make sure that the firewall is set to permit outbound traffic to flow to the Akamai cloud by configuring your outbound firewall to "ANY."
    If you do not update your firewall ahead of June 2016, you will be unable to process transactions after Phase Two is implemented.
    IP Address Considerations — If your solution connects to Authorize.Net directly via an IP address, you will need to update it to connect by domain name. Continuing to connect directly via an IP address is strongly discouraged as merchants will not receive the benefits of routing through Akamai, and could suffer a loss of service if transactions are re-routed among our various data centers.

Akamai is available for testing now in our sandbox environment. We strongly encourage you to test your solution prior to making any production change to ensure that you will not experience any disruptions to transaction processing.
Questions?

If you have any questions about the Akamai upgrade, please refer to our Akamai FAQs or contact Developer Support.

Thank you for your attention to this important email. We appreciate your ongoing partnership and are excited to bring you the benefits and reliability that this enhanced service provides.

Sincerely,
Authorize.Net

**Comment by kayladnls** [comment]
Yes, we should get this changed stat. I can work on it tonight.

**Comment by judgej** [comment]
For those looking for a workaround, when you create your gateway, new URLs can be passed in:

~~~php
$gateway = OmniPay::create('AuthorizeNet_AIM/SIM/DPM');
$gateway->setLiveEndpoint('https://secure2.authorize.net/gateway/transact.dll');
~~~

**Comment by barryvdh** [comment]
So these new url's can always be used, and it's just this line that needs changing? https://github.com/thephpleague/omnipay-authorizenet/blob/142a95f550a5320db09e66019ecf5c8b8c3885b9/src/AIMGateway.php#L24

If you can make a PR and test it, I see no problem in accepting it. But I don't have an Auth.net account, so I can't test it..
