### ISSUE TITLE
Restore use of invoice_num to its proper purpose

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-authorizenet#25]
The invoice_num field is used to put the `transactionId` into. This stops it being used to hold the invoice number. We should stop using this field in this way.

https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/AbstractRequest.php#L112

This would be a BC break for sites that are expecting to see the transaction ID in this field, so this change should be reserved for v3.0

A custom field `omnipay_transaction_id` currently takes on this function for the notify handler, though custom fields are not stored in the transaction log on the Authorize.Net account as `x_invoice_num` would be.  The application can decide how to use that field though, so they can carry on using it this way if they want.

**Comment by kyledye** [comment]
Was there any solution to this?  I'm trying to set the invoice_num and not having any luck. Any suggestions/examples of how to do this would be great.

**Comment by judgej** [comment]
I could have sworn invoice number was a standard OniPay Common field, but it appears not - unless my search-fu is up the spout today.

Yes, this driver needs to support invoice numbers in the long term, but it will invoice a BC break change. Which particular API are you using? There may be a workaround that involves feeding the invoice number into the message at the last moment.

**Comment by kyledye** [comment]
I'm using the AIM api, pretty new to this - is there something better?

**Comment by judgej** [comment]
The one you use depends on your requirements. I've not used the AIM API myself. If I understand it correctly, credit card details are posted to your site, and then your site posts them off to Authorize.Net. Because of that, you need good PCI compliance. If you don't have that, then *don't* use AIM. You *really* don't want those credit card details getting anywhere near your server.

Next up is SIM. That involves sending the user to the Authorize.net website to enter their CC details. Some merchants hate that. Personally, I much prefer it to giving an anonymous website those details.

Lastly is DPM. This is 90% the same as SIM, but you can put the payment form on your own site, but it still gets posted to the Authorize.net site. However, any errors are sent back to your site via a back channel and your site then decides what to do about it (e.g. present the form again with the error details).

There are pros and cons all around. DPM is more customised, but more complex to set up. SIM is easier, but you don't get to customise the payment screen. AIM is super-flexible, but has a very high PCI burden, so is only for big businesses with big money (even though every e-commerce site around has AIM plugins - they are being irresponsible IMO).

**Comment by judgej** [comment]
This actually got fixed for AIM and CIM with the move to XML.

It still remains with SIM and DPM, which still use the POST fields.

**Comment by judgej** [comment]
PR #66 merged to fix this - you can now use `setInvoiceNumber()` on CIM and DPM.

**Comment by judgej** [comment]
In release 2.5.0
