### ISSUE TITLE
Invalid response from payment gateway

### ISSUE THREAD

**Issue by brucewyne** [thephpleague/omnipay-authorizenet#37]
Keep getting the above error using AIM. Any indicators?

**Comment by judgej** [comment]
Where is this error appearing? Any details of the response that is invalid?

**Comment by brucewyne** [comment]
This happens after submitting an order and from AIMREsponse.php:29. 

I dumped the response and found it was because I wasn't passing a CVV.. my mistake :)

**Comment by judgej** [comment]
Closing - seems to be not-a-problem. Thanks for letting us know.
