### ISSUE TITLE
Akamai SureRoute

### ISSUE THREAD

**Issue by CaswellWC** [thephpleague/omnipay-authorizenet#42]
Authorize.net has been sending us emails saying that they strongly recommend that we update to use their new Akamai SureRoute service. Initially they were saying that after June 30th the old URL's would route automatically to the new service but now they are saying that they aren't going to do that anymore so if you want to use that service, you need to change the URL's that you are sending your messages to. The page they directed us to in order to make the necessary changes is http://www.authorize.net/support/akamaifaqs/. 
They are saying that there could be firewall issues that each merchant will need to consider if they are whitelisting IP addresses on outbound connections so if this change is made, you'll probably want to make it an option instead of just changing the URL's.

**Comment by judgej** [comment]
It looks like SIM uses the correct URL, but AIM needs updating:

https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/AIMGateway.php#L29

**Comment by judgej** [comment]
As an aside, you can set the URL through configuration if you want to force it in your application:

    $gateway = Omnipay::create('AuthorizeNet_AIM');
    $gateway->setLiveEndpoint('https://api2.authorize.net/xml/v1/request.api');

**Comment by judgej** [comment]
Accidental close. Will close when a release is made.

**Comment by judgej** [comment]
In release 2.5.0
