### ISSUE TITLE
CardReference can't set the cardCode

### ISSUE THREAD

**Issue by VinceG** [thephpleague/omnipay-authorizenet#51]
So here is a scenario:

a customer submits his credit card info on our form, we authorize and create a profile. at the end of the process he submits the form and we attempt to charge the card. We charge using the 'purchase' method under CIMGateway. The problem is we have the fraud suite enabled for CVV but we have no way of passing in the cardCode when we pass in the cardReference.

Example

```
$request = $this->getGateway()->purchase(['cardReference' => $cardReference, 'amount' => $amount, 'description' => $this->reservation->description]);
$data = $request->getData();
```

$data looks like this:

```

SimpleXMLElement Object
(
    [@attributes] => Array
        (
            [xmlns] => AnetApi/xml/v1/schema/AnetApiSchema.xsd
        )

    [merchantAuthentication] => SimpleXMLElement Object
        (
            [name] => xxxx
            [transactionKey] => xxxx
        )

    [transactionRequest] => SimpleXMLElement Object
        (
            [transactionType] => authCaptureTransaction
            [amount] => 327.00
            [profile] => SimpleXMLElement Object
                (
                    [customerProfileId] => xxxx
                    [paymentProfile] => SimpleXMLElement Object
                        (
                            [paymentProfileId] => xxxx
                        )

                )

            [order] => SimpleXMLElement Object
                (
                    [description] => AVN Reservation: Hard Rock Hotel & Casino Las Vegas for 3 nights (Oct 27, 2016 - Oct 30, 2016)
                )

            [transactionSettings] => SimpleXMLElement Object
                (
                    [setting] => SimpleXMLElement Object
                        (
                            [settingName] => testRequest
                            [settingValue] => false
                        )

                )

        )

)
```

Based on the documentation we can pass in cardCode as part of the profile->paymentProfile object but i am not sure if this is possible with the way it's currently setup.

https://developer.authorize.net/api/reference/index.html#payment-transactions-capture-a-previously-authorized-amount

This is an issue since it prevents from being able to validate the CVV and requires to turn it off to make the purchase pass. 

Any thoughts on this? i can also submit a PR for this.

I am thinking of forking this repository and maintaining it myself if i can't get these changes merged quickly.

Thanks for the help.

**Comment by judgej** [comment]
Certainly the way I would implement a change I need quickly, would be to fork and run from my fork to get it working. If you keep that fork on github, then the final changes can easily be merged back in later, with the advantage that it has been tested out in the field. So yeah, do that :-)

I'll have to look through the docs before I can comment further on this issue though.

**Comment by judgej** [comment]
PR #53 looks good, but there is one question about the serialisation of the `cardCode` - we need to be sure it is not going to get mixed up in storage when if the `CardReference` is serialised.

**Comment by judgej** [comment]
Closing as fixed.
