### ISSUE TITLE
Travis support PHP 7

### ISSUE THREAD

**Issue by VinceG** [thephpleague/omnipay-authorizenet#55]
PR will follow

**Comment by VinceG** [comment]
pushed as part of #52

**Comment by barryvdh** [comment]
Can you make a PR of that?

**Comment by judgej** [comment]
Good point - a separate PR will be automatically tested in travis and can be pull in quickly if it works, and separate fixes specifically for PHP 7 can be added to that PR if needed.

**Comment by VinceG** [comment]
@barryvdh @judgej a PR just for the Travis PHP 7 support?

**Comment by judgej** [comment]
Added in PR #52 

This was just merged and Travis is happy with the builds for PHP7 (but not HHVM yet - logts of *Creating default object from empty value* errors, which I believe are covered in another issue).
