### ISSUE TITLE
AIM Request -  pass customer email

### ISSUE THREAD

**Issue by nemmons** [thephpleague/omnipay-authorizenet#59]
Hello. Thanks for developing this library, I'm using it with great success. However, I would like to be able to pass the customer's email along with the purchase transaction API call (which triggers an automated payment receipt email from Authorize.net to each customer). 

I forked the repo and [modified AIMAbstractRequest](https://github.com/nemmons/omnipay-authorizenet/commit/650182569ec5ff1f325edd4b96de28abd4ecd7ad) to set `$req->customer->email` in the appropriate place. Is this something you're interested in integrating into your library?

**Comment by barryvdh** [comment]
Yes, please make a PR

**Comment by daniel-farina** [comment]
How can we pass the InvoiceNumber as well? I looked everywhere and I could not find such variable in the Omnipay package.

**Comment by judgej** [comment]
This has been merged now. I added the invoiceNumber at the same time, as it made sense. I couldn't find an invoice number field in OmniPay Common, though I could have sworn I remember there being one there. Probably just tired.

**Comment by judgej** [comment]
In release 2.5.0
