### ISSUE TITLE
Invoice number not being set in CIMAuthorizeRequest

### ISSUE THREAD

**Issue by MichaelMackus** [thephpleague/omnipay-authorizenet#69]
Looks like the new "invoiceNumber" parameter gets set in "addBillingData" which is [overridden in CIMAuthorizeRequest to do nothing](https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/CIMAuthorizeRequest.php#L40).

**Comment by judgej** [comment]
I think it needs to go here, just before the description:

https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/CIMAuthorizeRequest.php#L29

After the description, the optional `purchaseOrderNumber` could be supported too.

See the CIM XML guide, table 12: http://www.authorize.net/content/dam/authorize/documents/CIM_XML_guide.pdf

**Comment by judgej** [comment]
Are you in a position to be able to try that out? Something like:

~~~php
        $invoiceNumber = $this->getInvoiceNumber();
        if (!empty($invoiceNumber)) {
            $req->order->invoiceNumber = $invoiceNumber;
        }
~~~

**Comment by MichaelMackus** [comment]
Yes, that does seem to work fine. I haven't tested with an unset
invoiceNumber, not sure if that matters.

**Comment by judgej** [comment]
A pull request for this would be ideal, or I can tackle it, but that won't be until the New Year.

**Comment by judgej** [comment]
PR #71 was a brain-fart from me - it has been reverted in `master` (PR #72)

PR #73 contains the fix to this issue.

**Comment by judgej** [comment]
In release 2.5.0
