### ISSUE TITLE
AuthorizeNet_CIM

### ISSUE THREAD

**Issue by searl08** [thephpleague/omnipay-authorizenet#76]
Hi,

I am trying to setup a payment processor using omnipay-authorizenet AuthorizeNet_CIM.

I create the gateway object successfully and can make requests to the sandbox server.

Step 2 is to "create a card" for future use with Token Billing: $gateway->createCard() . This is successful.

From the general Omnipay Token Billing documentation:

**createCard($options) - returns a response object which includes a cardReference, which can be used for future transactions.** 

I don't see a specific 'cardReference' in the above createCard() response object.

So I create a $cardRef array and grab the returned response CustomerProfileId and CustomerPaymentProfileId . 

$profileResult['customerProfileId']=$response->getCustomerProfileId();
			
$profileResult['paymentProfileId']=$response->getCustomerPaymentProfileId();

Step 3 is a function to generate the purchase which fails:

`
function create_transaction($cardRef,$amount,$description,$invoice_number){
	
	global $status, $gateway;

	try {
		
		// Send purchase request
		$response = $gateway->purchase(
			array(
				'cardReference' => $cardRef ,				
				'amount' => $amount,
				'currency' => 'USD',				
				'description' => $_POST['description'],
				'transactionId' => $invoice_number
				
			)
		)->send();			
		if ($response->isSuccessful()) {
			
			// Payment was successful
			//echo 'Success: '.$response->getMessage();
			
			$status.='Success: '.$response->getMessage();

		} elseif ($response->isRedirect()) {
			
			// Redirect to offsite payment gateway
			$response->redirect();
		
		} else {		
	
			// Payment failed
			$status.='Transaction Failure: '.$response->getMessage();
			
		}		
		
	} catch (Exception $e) {
		
		$status.='<strong>Error:</strong> '.$e->getMessage(). "<br/>";
		
	}		
}
`
The purchase fails and when I look at the Response object it seems the Request  is not populating                   [cardReference] => Omnipay\AuthorizeNet\Model\CardReference Object
                        (
                            [customerProfileId:Omnipay\AuthorizeNet\Model\CardReference:private] => 
                            [paymentProfileId:Omnipay\AuthorizeNet\Model\CardReference:private] => 
                            [shippingProfileId:Omnipay\AuthorizeNet\Model\CardReference:private] => 
                        )

I am obviously not passing the correct data to the purchase method.

Any help would be greatly appreciated.

Thanks

Skip

**Comment by searl08** [comment]
I apparently needed to use the undocumented Omnipay method;

    $response->getCardReference();

to get a cardReference object to pass to my create_transaction() function.

All fixed.

Thanks

**Comment by judgej** [comment]
Glad you got it sorted.
