### ISSUE TITLE
Authorize.net dropping support for 3DES cypher

### ISSUE THREAD

**Issue by BridgingUnit** [thephpleague/omnipay-authorizenet#84]
Here's the [message from them](http://app.payment.authorize.net/e/es.aspx?s=986383348&e=1410656&elqTrackId=b4d9a2a0f1424fe28f720ff9d8ae4d54&elq=a5943305d7994e24abc641b2fd005d79&elqaid=580&elqat=1).

Does this affect the omnipay driver? Will it need updating, or is this something that won't affect functionality and security?

Thanks

**Comment by judgej** [comment]
Good question, and no, it won't affect the driver.

This is the encryption used in comminication from server to server, and from browser to server. So your merchant site - you shop - must be able to support TLS1.2, and have TLS1.0 and TLS1.1 disabled. When the gateway contacts your site, it will expect to use TLS1.2 as well.

There are other TLS and SSL requirements involved that I am not an expert in, so you may need to take advice from your hosting provider. But the bottom line is that this is about how your server talks to the end user browser, and to the payment gateway.

There are PCI checking services (mostly paid for, but some give free limited trials) that will exercice all the protocls on your server, and will warn you if any fail to meet the required standards.

**Comment by BridgingUnit** [comment]
Thanks for the quick response.

So it's the TLS 1.2 that's necessitating drop of 3DES, and that's not used in Omnipay, correct?

**Comment by judgej** [comment]
This Omnipay driver does not internally use any encryption. That is something the server deals with. You will need to check how the server is set up, and possibly make some configuration adjustments there.

**Comment by BridgingUnit** [comment]
Thanks for the confirmation. Have been checking in with host too.
