### ISSUE TITLE
AIMResponse->getTransactionId returns null

### ISSUE THREAD

**Issue by samlitowitz** [thephpleague/omnipay-authorizenet#95]
The function `getTransactionId` is [defined](https://github.com/thephpleague/omnipay-common/blob/ee7372cc1841bd943a2b51a6f44bbb580162a4a9/src/Common/Message/AbstractResponse.php#L150-L158) in the class [`AbstractResponse`](https://github.com/thephpleague/omnipay-common/blob/ee7372cc1841bd943a2b51a6f44bbb580162a4a9/src/Common/Message/AbstractResponse.php#L31) to return `null`. It is never overwritten by by the class [`AIMResponse`](https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/AIMResponse.php#L14). I propose it be overwritten to return the correct value.

**Comment by judgej** [comment]
Closed as fixed.
